### PR TITLE
Initial Bancho implementation

### PR DESCRIPTION
**Pull request by mempler**

### CODE REVIEW

**Comment by jacksonisiah** [comment]
Are we still sure that we are going to support Bancho protocols going forward? Wouldn't it be better to design our own system for communicating with the client, or do we just want to have drop in support with Akatsuki for now?

**Comment by mempler** [comment]
Qsor is ment to be a Drop-in replacement for osu!Stable. that way we can easily reuse existing code from lets say [Sora](https://github.com/Mempler/Sora) without planing the whole protocol all over again.

**Comment by mayacopeland** [comment]
Not attempting to cause drama here -- but what's the point in reusing peppy's protocol? wouldn't it be easier (and better) to create your own protocol?

It'd allow for more features faster, no?

**Comment by mempler** [comment]
That would make sense but like i said, that's what Protocol V20 is for. We want to keep osu!Stable supported for X amount of time after release. Prob until we have to break up support due to issues. It's much easier to reuse the same protocol and change it as needed.

**Pull request closed without merging**
